baseURL = 'https://vspdigital.github.io/'
languageCode = 'en-us'
theme = "anatole"
enableEmoji = true

[params]
title = 'Vranau Silviuuu'
author = "Silviu Vranau"
description = "iOS Mobile developerrrr"
profilePicture = "images/test.jpg"

