baseURL = 'https://silviuvr.github.io/'
languageCode = 'en-us'
theme = "anatole"
enableEmoji = true

[params]
title = 'Silviu Vranau'
author = "Silviu Vranau"
description = "iOS Developer | SwiftUI | Swift | Freelancer"
profilePicture = "images/profileImage.jpeg"


[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 200
  identifier = "blog"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
