baseURL = 'https://silviuvr.github.io/'
languageCode = 'en-us'
theme = "anatole"
enableEmoji = true

[params]
title = 'Silviu Vranau'
author = "Silviu Vranau"
description = "iOS Developer | SwiftUI | Swift | Freelancer"
profilePicture = "images/profileImage.jpeg"
mainSections = ["blog", "about"]

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 200
  identifier = "blog"
  url = "/blog/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"


## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/Silviuvr"


[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:vr.silviu@gmail.com"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/silviu-vranau/"
