baseURL = 'https://svpdigitalstudio.com/'
languageCode = 'en-us'
languageName = 'English'
theme = "anatole"
summaryLength = 25
enableEmoji = true
enableInlineShortcodes = true
enableRobotsTXT = true

pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
reversepagetitle = true
enableMediumZoom = false
displayMode = "dark"
hidesidebar = true
googleSiteVerify = "EMo_0IvtzF8Ez5RqqS5asjRhFLdX-iyHbrcyNnMYmBU"
title = 'Silviu Vranau'
author = "SVPDigitalStudio"
description = "iOS Developer | SwiftUI | Swift | Freelancer"
profilePicture = "images/profileImage.jpeg"
mainSections = ["blog"]
readMore = true
contentratio = 0.75
copyright = "SVPDigitalStudio, 2019-{{ YEAR }}"
doNotLoadAnimations = true
contactFormAction = "https://formspree.io/f/mblrdjlw"
customCss = ["css/styles.css"]
customJs = ["js/custom.js", "js/addAuthorData.js"]
favicon = "favicons/"
singleDateFormat = "Jan 2, 2006"
indexDateFormat = "Jan 2, 2006"
listDateFormat = "Jan 2, 2006"


[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"


  [[menu.main]]
  name = "Blog"
  weight = 200
  identifier = "blog"
  url = "/blog/"

 
  [[menu.main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[menu.main]]
  name = "Reviews"
  weight = 400
  identifier = "reviews"
  url = "/reviews/"

 [[menu.main]]
  name = "About"
  weight = 500
  identifier = "about"
  url = "/about/"


 [[menu.main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact/"

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/Silviuvr"


[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:vr.silviu@gmail.com"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/silviu-vranau/"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true